#!/bin/sh
# mpdnotify - popup notification of current playing song
# this file is in public domain

musicdir="${MUSICDIR:-$XDG_MUSIC_DIR}"
cachedir="${CACHEDIR:-$XDG_CACHE_HOME}"
cachedir="${cachedir:-$HOME/.cache}"
coverfile="$CACHEDIR/cover.png"

test -n "$XNOTIFY_FIFO" || { echo 'mpdnotify: $XNOTIFY_FIFO not set' >&2 && exit 1; }
test -n "$MUSICDIR" || { echo 'mpdnotify: $MUSICDIR not set' >&2 && exit 1; }
test -n "$CACHEDIR" || { echo 'mpdnotify: $CACHEDIR not set' >&2 && exit 1; }
trap 'rm -f $coverfile' EXIT
while s="$(mpc current --wait -f 'TAG:mpd\t%artist%\t%album%\t[[%title%]|[%name%]|[%file%]]')"
do
	if ffmpeg -y -i "$musicpath/$(mpc current -f '%file%')" -f image2 "$coverfile" 2>/dev/null
	then
		printf 'IMG:%s\t%s\n' "$coverfile" "$s" >"$XNOTIFY_FIFO"
	else
		printf '%s\n' "$s" >"$XNOTIFY_FIFO"
	fi
done
