#!/bin/sh
# run - run a .desktop file
# this file in public domain

iflag=0
apppath=${APPPATH:-/usr/local/share/applications:/usr/share/applications}
appiconpath=${APPICONPATH:-/usr/local/share/icons/hicolor/48x48:/usr/share/icons/hicolor/48x48}
termcmd=${TERMCMD:-xterm}
origifs="$IFS"

# get desktop files
getfiles() {
	IFS=:
	for dir in $apppath
	do
		grep -iL "NoDisplay=true" "$dir"/*.desktop 2>/dev/null
	done
	IFS="$origifs"
}

# get icon path
geticon() {
	IFS=:
	for dir in $appiconpath
	do
		file="$dir/$1.png"
		[ -f "$file" ] && echo "$file" && return
	done
	IFS="$origifs"
}

# get application names
getapps() {
	for file in $(getfiles)
	do
		icon="$(sed -n "/^\[Desktop Entry\]$/,/^Icon *=/{/^Icon *=/{s/^Icon *= *//;p;};}" "$file")"
		icon="$(geticon "$icon")"
		if [ $iflag -eq 1 -a -n "$icon" ]
		then
			printf 'IMG:%s\t' "$icon"
			printf "%s" "$file" | sed 's:^\([^/]*/\)*\(.*\.\)*\([^.]*\)\.desktop$:\3:'
		else
			printf "%s" "$file" | sed 's:^\([^/]*/\)*\(.*\.\)*\([^.]*\)\.desktop$:\3:'
			comment="$(sed -n "/^\[Desktop Entry\]$/,/^Comment *=/{/^Comment *=/{s/^Comment *= *//;p;};}" "$file")"
			[ -n "$comment" ] && printf "\t%s" "$comment"
		fi
		echo
	done
}

# run an application
run() {
	term="$(sed -n "/^\[Desktop Entry\]$/,/^Terminal *=/{/^Terminal *=/{s/^Terminal *=//;p;};}" "$1")"
	cmd="$(sed -n "/^\[Desktop Entry\]$/,/^Exec *=/{/^Exec *=/{s/^Exec *=//;s/ *%[uUFf].*//;p;};}" "$1")"
	shift
	trap "" 1 15
	if [ "$term" = "true" ]
	then
		exec $TERMCMD -e sh -c "$cmd $@" &
	else
		exec sh -c "$cmd $@" &
	fi
}

if [ "$1" = '-i' ]
then
	iflag=1
	shift
fi

case "$#" in
0)
	getapps
	;;
*)
	if [ -f "$1" ]
	then
		desktopfile="$1"
	else
		desktopfile="$(getfiles | egrep -m 1 "^([^/]*/)*(.*\.)*$1\.desktop$")"
		[ -z "$desktopfile" ] && echo "unknown application" >&2 && exit 1
	fi
	shift
	run "$desktopfile" $@
	;;
esac

exit 0
