#!/bin/sh
# run - run a .desktop file
# this file in public domain

apppath=${APPPATH:-/usr/local/share/applications:/usr/share/applications}
termcmd=${TERMCMD:-xterm}

# get desktop files
getfiles() {
	IFS=:
	for dir in $apppath
	do
		fgrep -iL "NoDisplay=true" "$dir"/*.desktop 2>/dev/null
	done
}

# get application names
getapps() {
	awk '
	function basename(s) {
		sub(/.*\//, "", s)
		sub(/\.desktop$/, "", s)
		sub(/.*\./, "", s)
		return s
	}

	BEGIN {
		FS = " *= *"
		OFS = " - "
	}

	FNR == 1 {
		apps[FILENAME] = ""
	}

	$1 == "Comment" || ($1 == "GenericName" && apps[FILENAME] == "") {
		apps[FILENAME] = $2
	}

	END {
		for (i in apps) {
			print basename(i), apps[i]
		}
	}
	' "$@"
}

# run an application
run() {

	file="$1"
	shift
	cmd="$(sed -n "/^\[Desktop Entry\]$/,/^Exec *=/{/^Exec *=/{s/^Exec *=//;s/ *%[uUFf].*//;p;};}" "$file")"
	if egrep -s 'Terminal *= *true' "$file"
	then
		exec "$termcmd" -e sh -c "$cmd $*" &
	else
		exec sh -c "exec $cmd $*" &
	fi
}

case "$#" in
0)
	getapps `getfiles`
	;;
*)
	if [ -f "$1" ]
	then
		desktopfile="$1"
	else
		desktopfile="$(getfiles | egrep -m 1 "^([^/]*/)*(.*\.)*$1\.desktop$")"
		[ -z "$desktopfile" ] && echo "unknown application" >&2 && exit 1
	fi
	shift
	run "$desktopfile" $@
	;;
esac

exit 0
