.TH XMAN 1
.SH NAME
xman \- open man pages in zathura
.SH SYNOPSIS
.B xman
.RI [[ session "] " manpages... ]
.SH DESCRIPTION
.B xman
opens the given manual pages in zathura.
.PP
.B xman
has the same command line syntax of man(1),
except that, when no argument is given,
xman(1) lists all available manual pages followed by their description separated with a tab character.
.SH SEE ALSO
.IR man (1),
.IR zathura (1)
